#!/bin/bash

branch=$1
branchingPoint=`diff -u <(git rev-list --first-parent $branch --max-count=15000) <(git rev-list --first-parent master --max-count=15000) | sed -ne 's/^ //p' | head -1`
$PYCHARMER_DIR/get_todos_by_file.py $branch $branchingPoint
