#!/bin/bash

branch=$1
branchingPoint=`diff -u <(git rev-list --first-parent $branch --max-count=15000) <(git rev-list --first-parent master --max-count=15000) | sed -ne 's/^ //p' | head -1`
todos=`git diff $branchingPoint $1  | grep '^+' | grep TODO`
if [[ $todos ]]; then
	echo "TODO list:"
	echo "$todos"
fi
